/**
 * Writes docs/SEPTEMBER-REVIEW.md: what the app now believes about September,
 * read back out of data/ingredients/ rather than from the source table, so the
 * list shows what was actually written. This is the artefact issue 004 asks
 * Tia to review.
 */
import fs from 'node:fs'
import path from 'node:path'

import { SEPTEMBER_BY_INGREDIENT } from './september-source.mjs'

const SEPTEMBER = 9
const DIR = path.join(process.cwd(), 'data', 'ingredients')

const ingredients = fs.readdirSync(DIR)
  .filter((f) => f.endsWith('.json'))
  .map((f) => JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8')))
  .sort((a, b) => a.id.localeCompare(b.id))

const has = (months, month) => Array.isArray(months) && months.includes(month)
const source = (id) => {
  const slug = SEPTEMBER_BY_INGREDIENT[id]?.[1]
  return slug ? `[${slug}](https://satokausi.fi/raaka-aineet/${slug}/)` : '—'
}
const drafted = (i) => (i.verified ? (has(i.unverifiedMonths, SEPTEMBER) ? 'drafted' : 'Tia') : 'drafted')

const fresh = []
const storage = []
const imported = []
const notInSeason = []
const noSource = []

for (const i of ingredients) {
  const d = i.availability.domestic
  const row = { i, source: source(i.id), who: drafted(i) }
  if (has(d?.freshMonths, SEPTEMBER)) fresh.push({ ...row, peak: has(d?.peakMonths, SEPTEMBER) })
  else if (has(d?.storageMonths, SEPTEMBER)) storage.push(row)
  else if (has(i.availability.imported?.months, SEPTEMBER)) imported.push(row)
  else if (SEPTEMBER_BY_INGREDIENT[i.id]?.[0] === 'no-page') noSource.push(row)
  else if (SEPTEMBER_BY_INGREDIENT[i.id]) notInSeason.push(row)
}

// Sorted by display name, not id: the reviewer reads names, and some names are
// Finnish while every id is an English slug.
// `who` is dropped where nothing was written, since there is no claim to attribute.
const table = (rows, { who = true } = {}) => [
  `| Ingredient | Category | Sourced from |${who ? ' Who says so |' : ''}`,
  `| --- | --- | --- |${who ? ' --- |' : ''}`,
  ...[...rows]
    .sort((a, b) => a.i.name.localeCompare(b.i.name, 'fi'))
    .map((r) =>
      `| ${r.i.name}${r.peak ? ' **(peak)**' : ''} | ${r.i.category} | ${r.source} |` +
      (who ? ` ${r.who} |` : '')),
].join('\n')

const doc = `# September, as the app now has it

Generated by \`node scripts/september-review.mjs\`. Every month here was read off
that ingredient's own page on satokausi.fi (issue 004). "Who says so" is **Tia**
where September was already in her own Notion data and **drafted** where this
slice added it — drafted months carry the unverified marker until she confirms
them.

Provenance is per month, not per claim: bok choy's September is Tia's own, and
satokausi's peak marking on it rides along unmarked rather than demoting her
month to drafted.

Ingredients in \`nut\` and \`other\` have no season and are left out.

## Fresh in September (${fresh.length})

Finnish produce actually being harvested or picked this month. **(peak)** marks
satokausi's Huippusesonki: best quality and price.

${table(fresh)}

## From Finnish storage in September (${storage.length})

Available, but not fresh. The app should say so rather than call these in season.

${table(storage)}

## Worth buying imported in September (${imported.length})

${table(imported)}

## Not in season in September (${notInSeason.length})

satokausi's page for these lists September under no heading at all.

${table(notInSeason, { who: false })}

## No source found (${noSource.length})

satokausi has no page for these, so nothing was written. They keep whatever
months they already had.

${table(noSource, { who: false })}
`

fs.writeFileSync(path.join(process.cwd(), 'docs', 'SEPTEMBER-REVIEW.md'), doc)
console.log(`fresh ${fresh.length}, storage ${storage.length}, imported ${imported.length}, not in season ${notInSeason.length}, no source ${noSource.length}`)
