/**
 * Writes docs/YEAR-REVIEW.md: what the app now believes about May to August
 * and October to December, read back out of data/ingredients/ rather than from
 * the source, so the list shows what was actually written. This is the
 * artefact issue 012 asks Tia to review, as SEPTEMBER-REVIEW.md was for 004.
 *
 * The "left for Tia" section is the dry-run report of apply-year.mjs, rerun
 * here so the two cannot drift apart.
 */
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'

import { yearSlugs } from './year-slugs.mjs'

const MONTHS = [5, 6, 7, 8, 10, 11, 12]
const NAMES = ['', 'January', 'February', 'March', 'April', 'May', 'June', 'July',
  'August', 'September', 'October', 'November', 'December']
const DIR = path.join(process.cwd(), 'data', 'ingredients')
const SEASONAL = ['vegetable', 'fruit', 'berry', 'mushroom', 'herb']

const slugs = { ...yearSlugs(), chanterelle: 'kantarelli' }
const ingredients = fs
  .readdirSync(DIR)
  .map((f) => JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8')))
  .filter((i) => SEASONAL.includes(i.category))
  .sort((a, b) => a.name.localeCompare(b.name, 'fi'))

const link = (id) =>
  slugs[id] ? `[${slugs[id]}](https://satokausi.fi/raaka-aineet/${slugs[id]}/)` : 'no page'

const drafted = (i, month) => !i.verified || (i.unverifiedMonths ?? []).includes(month)

function status(i, month) {
  const d = i.availability.domestic
  const im = i.availability.imported
  const parts = []
  if (d?.freshMonths.includes(month)) parts.push(d.peakMonths?.includes(month) ? 'fresh **(peak)**' : 'fresh')
  if (d?.storageMonths.includes(month)) parts.push('from storage')
  if (im?.months.includes(month)) {
    const origin = im.origins?.find((o) => o.months.includes(month))
    parts.push(origin ? `imported: ${origin.countries.join(', ')}` : 'imported')
  }
  return parts.join('; ')
}

const report = execFileSync('node', ['scripts/apply-year.mjs'], { encoding: 'utf8' })
const section = (key) => {
  const m = report.match(new RegExp(`## ${key} \\(\\d+\\)\\n((?:- .*\\n)*)`))
  return (m?.[1] ?? '').trim()
}

let out = `# The rest of the year, as the app now has it

Generated by \`node scripts/year-review.mjs\`. Every month here was read off
that ingredient's own page on satokausi.fi on 2026-09-30 (issue 012), the same
pages issue 004 read for September. "Who says so" is **Tia** where the month was
already in her own data and **drafted** where issue 012 added it. Tia decided
not to review these one by one (\`docs/DECISIONS.md\`, 2026-09-30); this file is
the record of what was read, for checking when something looks wrong.

January to April (Tia's Notion months) and September (issue 004, reviewed in
\`docs/SEPTEMBER-REVIEW.md\`) are not repeated here. Where satokausi disagrees
with January to April, that is \`docs/SATOKAUSI-CONFLICTS.md\` and issue 013.

Ingredients in \`nut\` and \`other\` have no season and are left out.

## Left for Tia

**Months the page does not settle.** satokausi lists the month but gives no
origin flag, so it is not known whether it is Finnish or imported, or the flag
is not a country code. Nothing was written for these months.

${section('unsettled')}

For romanesco, "EPS" is almost certainly a typo for ESP (Spain); it is left
out rather than corrected on a guess.

**No satokausi page.** Nothing written; their months need another source or
Tia.

${section('noPage')}

**Pages with a sentence instead of a table.** Button mushroom (herkkusieni)
and oyster mushroom (osterivinokas) say "grown in Finland year round" rather
than listing months, so every month is filled as fresh and Finnish. Their
January to April is not touched here: Tia's Notion data had none, and adding it
would change her months, which is issue 013's to decide.
${section('noTable') ? `\nAny other page with no season table, nothing written:\n\n${section('noTable')}\n` : ''}

**Months Tia had already verified, left as they were.** satokausi also covers
these; her data wins.

${section('keptVerified')}
`

for (const month of MONTHS) {
  const rows = ingredients
    .map((i) => ({ i, s: status(i, month) }))
    .filter(({ s }) => s)
  out += `\n## ${NAMES[month]} (${rows.length})\n\n`
  out += '| Ingredient | Category | In the app | Sourced from | Who says so |\n'
  out += '| --- | --- | --- | --- | --- |\n'
  for (const { i, s } of rows) {
    out += `| ${i.name} | ${i.category} | ${s} | ${link(i.id)} | ${drafted(i, month) ? 'drafted' : 'Tia'} |\n`
  }
}

fs.writeFileSync(path.join(process.cwd(), 'docs', 'YEAR-REVIEW.md'), out)
console.log('Wrote docs/YEAR-REVIEW.md')
